# AWS Configuration for RevHub Services

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://revhub-db.cluster-xyz.us-east-1.rds.amazonaws.com:3306/revhub_auth
    username: admin
    password: ${DB_PASSWORD}
  
  data:
    mongodb:
      uri: mongodb://admin:${MONGO_PASSWORD}@revhub-mongo.cluster-xyz.us-east-1.docdb.amazonaws.com:27017/revhub_posts
    
    elasticsearch:
      repositories:
        enabled: true

# Elasticsearch Configuration
elasticsearch:
  host: search-revhub-search-xyz.us-east-1.es.amazonaws.com
  port: 443
  protocol: https

# AWS S3 Configuration
aws:
  s3:
    bucket: revhub-deployment-rameezshaik
    region: us-east-1
  
# Service Discovery (AWS ELB)
eureka:
  client:
    service-url:
      defaultZone: http://revhub-elb-123456789.us-east-1.elb.amazonaws.com:8761/eureka